services:
  - type: web
    name: terminal-start-server
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
